apiVersion: v1
kind: Service
metadata:
  namespace: employee-service
  labels:
    app: employee-service
  name: employee-service
spec:
  ports:
  
    - protocol: TCP
      port: 8000
      targetPort: 8000
   
   
  selector:
    app: employee-service
  type: ClusterIP
